application: twittertrove
version: 1
runtime: python
api_version: 1

handlers:
- url: /static/
  static_dir: static

- url: /_ah/queue/deferred
  script: $PYTHON_LIB/google/appengine/ext/deferred/handler.py

- url: /.*
  script: main.py
