application: tweetlocker
version: 1b001
runtime: python
api_version: 1

handlers:
- url: /(favicon\.ico|robots\.txt)
  static_files: static/\1
  upload: static/(favicon\.ico|robots\.txt)

- url: /static/
  static_dir: static

- url: /_ah/queue/deferred
  script: deferred.py

- url: /_/shell
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /.*
  script: main.py
