application: tweetlocker
version: 1b001
runtime: python
api_version: 1

handlers:
- url: /(favicon\.ico|robots\.txt)
  static_files: static/\1
  upload: static/(favicon\.ico|robots\.txt)

- url: /static/
  static_dir: static

- url: /_ah/queue/deferred
  script: deferred.py

- url: /_/shell
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /.*
  script: main.py

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- static/ext/blueprint/(AUTHORS.textile|LICENSE|TUTORIAL.textile|lib|tests|CHANGELOG|README.textile|templates)
